create table if not exists benchmark_data (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('Wedding','Naming Ceremony','Burial / Memorial','Corporate Event')),
  city text not null check (city in ('Lagos','Abuja','Port Harcourt')),
  style_tier text not null check (style_tier in ('Essential','Classic','Premium')),
  category text not null,
  pct_of_total numeric(5,2) not null check (pct_of_total > 0 and pct_of_total <= 100),
  sample_size integer not null default 0 check (sample_size >= 0),
  unique(event_type, city, style_tier, category)
);

alter table benchmark_data enable row level security;
drop policy if exists "public can read benchmark data" on benchmark_data;
create policy "public can read benchmark data" on benchmark_data for select using (true);
